using System.Globalization;
using System.IO;
using System.IO.Packaging;
using System.Text;
using System.Xml;
using Serilog;
using Stratus.Desktop.Models;

namespace Stratus.Desktop.Services;

/// <summary>
/// Exports weather data to Excel (.xlsx) format using Open XML without external libraries.
/// Creates a valid OOXML SpreadsheetML document with headers and styled data.
/// </summary>
public static class ExcelExportService
{
    private const string NsSpreadsheet = "http://schemas.openxmlformats.org/spreadsheetml/2006/main";
    private const string NsRelationships = "http://schemas.openxmlformats.org/officeDocument/2006/relationships";
    private const string NsContentTypes = "http://schemas.openxmlformats.org/package/2006/content-types";

    public static void Export(List<WeatherRecord> records, WeatherStation? station, string filePath)
    {
        Log.Information("Exporting {Count} records to Excel: {Path}", records.Count, filePath);

        // Determine which columns have data
        var columns = BuildColumnList(records);

        using var package = Package.Open(filePath, FileMode.Create, FileAccess.ReadWrite);

        // Content Types
        WriteContentTypes(package);

        // Relationships
        WriteRelationships(package);

        // Shared strings
        var sharedStrings = BuildSharedStrings(columns, station);
        WriteSharedStrings(package, sharedStrings);

        // Worksheet
        WriteWorksheet(package, records, columns, sharedStrings);

        // Workbook
        WriteWorkbook(package);

        // Workbook relationships
        WriteWorkbookRelationships(package);

        Log.Information("Excel export complete: {Path}", filePath);
    }

    private static List<ExcelColumn> BuildColumnList(List<WeatherRecord> records)
    {
        var all = new List<ExcelColumn>
        {
            new("Timestamp", "yyyy-MM-dd HH:mm:ss", r => r.Timestamp.ToString("yyyy-MM-dd HH:mm:ss")),
            new("Temperature (°C)", "F2", r => r.Temperature?.ToString("F2", CultureInfo.InvariantCulture)),
            new("Humidity (%)", "F1", r => r.Humidity?.ToString("F1", CultureInfo.InvariantCulture)),
            new("Pressure (hPa)", "F1", r => r.Pressure?.ToString("F1", CultureInfo.InvariantCulture)),
            new("Wind Speed (m/s)", "F1", r => r.WindSpeed?.ToString("F1", CultureInfo.InvariantCulture)),
            new("Wind Direction (°)", "F0", r => r.WindDirection?.ToString("F0", CultureInfo.InvariantCulture)),
            new("Wind Gust (m/s)", "F1", r => r.WindGust?.ToString("F1", CultureInfo.InvariantCulture)),
            new("Rainfall (mm)", "F2", r => r.Rainfall?.ToString("F2", CultureInfo.InvariantCulture)),
            new("Solar Radiation (W/m²)", "F0", r => r.SolarRadiation?.ToString("F0", CultureInfo.InvariantCulture)),
            new("UV Index", "F1", r => r.UvIndex?.ToString("F1", CultureInfo.InvariantCulture)),
            new("Dew Point (°C)", "F2", r => r.DewPoint?.ToString("F2", CultureInfo.InvariantCulture)),
            new("ETo (mm/day)", "F3", r => r.Eto?.ToString("F3", CultureInfo.InvariantCulture)),
            new("Soil Temperature (°C)", "F1", r => r.SoilTemperature?.ToString("F1", CultureInfo.InvariantCulture)),
            new("Soil Moisture (%)", "F1", r => r.SoilMoisture?.ToString("F1", CultureInfo.InvariantCulture)),
            new("Battery Voltage (V)", "F2", r => r.BatteryVoltage?.ToString("F2", CultureInfo.InvariantCulture)),
            new("Water Level (mm)", "F1", r => r.WaterLevel?.ToString("F1", CultureInfo.InvariantCulture)),
            new("PM2.5 (µg/m³)", "F1", r => r.Pm25?.ToString("F1", CultureInfo.InvariantCulture)),
            new("PM10 (µg/m³)", "F1", r => r.Pm10?.ToString("F1", CultureInfo.InvariantCulture)),
            new("CO₂ (ppm)", "F0", r => r.Co2?.ToString("F0", CultureInfo.InvariantCulture)),
            new("QC Flag", "", r => r.QcFlag >= 0 ? r.QcFlag.ToString() : null),
        };

        // Only include columns that have at least one non-null value
        return all.Where(c =>
            c.Header == "Timestamp" || c.Header == "QC Flag" ||
            records.Any(r => !string.IsNullOrEmpty(c.GetValue(r)))
        ).ToList();
    }

    private static Dictionary<string, int> BuildSharedStrings(List<ExcelColumn> columns, WeatherStation? station)
    {
        var strings = new Dictionary<string, int>();
        int idx = 0;

        // Station info
        if (station != null)
        {
            strings[$"Station: {station.Name}"] = idx++;
            strings[$"Location: {station.Latitude:F6}, {station.Longitude:F6}"] = idx++;
        }
        strings["Generated by Stratus Weather Station Manager"] = idx++;

        // Column headers
        foreach (var col in columns)
        {
            if (!strings.ContainsKey(col.Header))
                strings[col.Header] = idx++;
        }

        return strings;
    }

    private static void WriteContentTypes(Package package)
    {
        // The Package class auto-generates [Content_Types].xml
    }

    private static void WriteRelationships(Package package)
    {
        package.CreateRelationship(
            new Uri("/xl/workbook.xml", UriKind.Relative),
            TargetMode.Internal,
            "http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument",
            "rId1");
    }

    private static void WriteWorkbook(Package package)
    {
        var uri = new Uri("/xl/workbook.xml", UriKind.Relative);
        var part = package.CreatePart(uri,
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml");

        using var stream = part.GetStream();
        using var writer = XmlWriter.Create(stream, new XmlWriterSettings { Indent = true, Encoding = Encoding.UTF8 });

        writer.WriteStartDocument();
        writer.WriteStartElement("workbook", NsSpreadsheet);
        writer.WriteAttributeString("xmlns", "r", null, NsRelationships);

        writer.WriteStartElement("sheets", NsSpreadsheet);
        writer.WriteStartElement("sheet", NsSpreadsheet);
        writer.WriteAttributeString("name", "Weather Data");
        writer.WriteAttributeString("sheetId", "1");
        writer.WriteAttributeString("r", "id", NsRelationships, "rId1");
        writer.WriteEndElement(); // sheet
        writer.WriteEndElement(); // sheets

        writer.WriteEndElement(); // workbook
        writer.WriteEndDocument();
    }

    private static void WriteWorkbookRelationships(Package package)
    {
        var wbUri = new Uri("/xl/workbook.xml", UriKind.Relative);
        var wbPart = package.GetPart(wbUri);

        wbPart.CreateRelationship(
            new Uri("worksheets/sheet1.xml", UriKind.Relative),
            TargetMode.Internal,
            "http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet",
            "rId1");

        wbPart.CreateRelationship(
            new Uri("sharedStrings.xml", UriKind.Relative),
            TargetMode.Internal,
            "http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings",
            "rId2");
    }

    private static void WriteSharedStrings(Package package, Dictionary<string, int> strings)
    {
        var uri = new Uri("/xl/sharedStrings.xml", UriKind.Relative);
        var part = package.CreatePart(uri,
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml");

        using var stream = part.GetStream();
        using var writer = XmlWriter.Create(stream, new XmlWriterSettings { Indent = true, Encoding = Encoding.UTF8 });

        writer.WriteStartDocument();
        writer.WriteStartElement("sst", NsSpreadsheet);
        writer.WriteAttributeString("count", strings.Count.ToString());
        writer.WriteAttributeString("uniqueCount", strings.Count.ToString());

        foreach (var kvp in strings.OrderBy(k => k.Value))
        {
            writer.WriteStartElement("si", NsSpreadsheet);
            writer.WriteStartElement("t", NsSpreadsheet);
            writer.WriteString(kvp.Key);
            writer.WriteEndElement(); // t
            writer.WriteEndElement(); // si
        }

        writer.WriteEndElement(); // sst
        writer.WriteEndDocument();
    }

    private static void WriteWorksheet(Package package, List<WeatherRecord> records,
        List<ExcelColumn> columns, Dictionary<string, int> sharedStrings)
    {
        var uri = new Uri("/xl/worksheets/sheet1.xml", UriKind.Relative);
        var part = package.CreatePart(uri,
            "application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml");

        using var stream = part.GetStream();
        using var writer = XmlWriter.Create(stream, new XmlWriterSettings { Indent = false, Encoding = Encoding.UTF8 });

        writer.WriteStartDocument();
        writer.WriteStartElement("worksheet", NsSpreadsheet);

        // Column widths
        writer.WriteStartElement("cols", NsSpreadsheet);
        writer.WriteStartElement("col", NsSpreadsheet);
        writer.WriteAttributeString("min", "1");
        writer.WriteAttributeString("max", "1");
        writer.WriteAttributeString("width", "20");
        writer.WriteAttributeString("bestFit", "1");
        writer.WriteEndElement();
        for (int i = 2; i <= columns.Count; i++)
        {
            writer.WriteStartElement("col", NsSpreadsheet);
            writer.WriteAttributeString("min", i.ToString());
            writer.WriteAttributeString("max", i.ToString());
            writer.WriteAttributeString("width", "14");
            writer.WriteEndElement();
        }
        writer.WriteEndElement(); // cols

        writer.WriteStartElement("sheetData", NsSpreadsheet);

        // Header row
        int rowIdx = 1;
        writer.WriteStartElement("row", NsSpreadsheet);
        writer.WriteAttributeString("r", rowIdx.ToString());
        for (int c = 0; c < columns.Count; c++)
        {
            WriteStringCell(writer, rowIdx, c, sharedStrings[columns[c].Header]);
        }
        writer.WriteEndElement(); // row

        // Data rows
        var ordered = records.OrderBy(r => r.Timestamp).ToList();
        foreach (var record in ordered)
        {
            rowIdx++;
            writer.WriteStartElement("row", NsSpreadsheet);
            writer.WriteAttributeString("r", rowIdx.ToString());

            for (int c = 0; c < columns.Count; c++)
            {
                var val = columns[c].GetValue(record);
                if (val == null) continue;

                if (columns[c].Header == "Timestamp")
                {
                    // Write timestamp as string
                    WriteInlineStringCell(writer, rowIdx, c, val);
                }
                else if (double.TryParse(val, NumberStyles.Any, CultureInfo.InvariantCulture, out var num))
                {
                    WriteNumberCell(writer, rowIdx, c, num);
                }
                else
                {
                    WriteInlineStringCell(writer, rowIdx, c, val);
                }
            }

            writer.WriteEndElement(); // row
        }

        writer.WriteEndElement(); // sheetData
        writer.WriteEndElement(); // worksheet
        writer.WriteEndDocument();
    }

    private static string ColRef(int col)
    {
        var result = "";
        col++; // 1-based
        while (col > 0)
        {
            col--;
            result = (char)('A' + col % 26) + result;
            col /= 26;
        }
        return result;
    }

    private static void WriteStringCell(XmlWriter w, int row, int col, int ssIdx)
    {
        w.WriteStartElement("c", NsSpreadsheet);
        w.WriteAttributeString("r", $"{ColRef(col)}{row}");
        w.WriteAttributeString("t", "s");
        w.WriteElementString("v", NsSpreadsheet, ssIdx.ToString());
        w.WriteEndElement();
    }

    private static void WriteNumberCell(XmlWriter w, int row, int col, double value)
    {
        w.WriteStartElement("c", NsSpreadsheet);
        w.WriteAttributeString("r", $"{ColRef(col)}{row}");
        w.WriteElementString("v", NsSpreadsheet, value.ToString(CultureInfo.InvariantCulture));
        w.WriteEndElement();
    }

    private static void WriteInlineStringCell(XmlWriter w, int row, int col, string value)
    {
        w.WriteStartElement("c", NsSpreadsheet);
        w.WriteAttributeString("r", $"{ColRef(col)}{row}");
        w.WriteAttributeString("t", "inlineStr");
        w.WriteStartElement("is", NsSpreadsheet);
        w.WriteElementString("t", NsSpreadsheet, value);
        w.WriteEndElement(); // is
        w.WriteEndElement(); // c
    }

    private record ExcelColumn(string Header, string Format, Func<WeatherRecord, string?> GetValue);
}
