#!/usr/bin/env python3
# ===========================================================================
#
#  Stratus AS3935 Lightning Detection System
#  Campbell UART terminal identification probe
#
#  Property of METRON (PTY) LTD | Inteltronics
#  Developed by L.J. Esterhuizen, Inteltronics
#
# ===========================================================================
#
#  WHY THIS EXISTS
#
#  The Quaggasklip unit is a Raspberry Pi Zero W on a Pi 2 Click Shield
#  (MIKROE-1879), which carries two mikroBUS sockets:
#
#      socket 1   AS3935 lightning sensor  (SPI, IRQ on BCM 17)
#      socket 2   Terminal 2 Click         (MIKROE-4951)
#
#  Terminal 2 Click is passive. It contains no transceiver and no logic: it
#  simply mirrors the sixteen mikroBUS pins of the socket it sits in onto two
#  nine-position screw terminals. So the label silkscreened next to a terminal
#  describes the mikroBUS pin, NOT which Raspberry Pi GPIO is behind it.
#
#  THE TRAP THIS AVOIDS
#
#  The obvious thing to do when wiring a logger is to use the terminal marked
#  TX. On this build that is the wrong terminal, twice over:
#
#    1. mikroBUS TX is wired to the Pi's hardware UART0 TXD, BCM 14. On this
#       unit BCM 14/15 is the SERIAL CONSOLE - config.txt sets enable_uart=1
#       and keeps it as the recovery path for a site with no display. Wiring a
#       Campbell logger there does not just fail to carry the lightning record,
#       it feeds kernel and login-prompt text into the logger's serial port.
#
#    2. The Campbell output is not the hardware UART at all. It is a bit-banged
#       UART generated by pigpio's wave_add_serial on whichever GPIO
#       campbell_uart_tx_pin names, which is BCM 26 by default. That was chosen
#       precisely so the recovery console stays usable.
#
#  So the correct terminal is the one carrying BCM 26, and which mikroBUS pin
#  that is depends on the shield's routing rather than on anything visible on
#  the Terminal 2 board.
#
#  WHAT THIS DOES
#
#  Rather than depending on a schematic that is not to hand at a site, this
#  toggles the configured pin slowly enough to find with a multimeter or a logic
#  probe, so the installer can identify the terminal empirically and label it.
#  Then it sends a real record in the detector's own format so the logger end
#  can be confirmed before anybody leaves.
#
#  USAGE
#
#      sudo systemctl stop lightning-detector       # release the pin first
#      python3 campbell_pin_probe.py --toggle       # find the terminal
#      python3 campbell_pin_probe.py --send         # send one test record
#      sudo systemctl start lightning-detector
#
#  Stopping the service matters: pigpio will happily let two writers drive one
#  GPIO, and the result is a corrupted waveform that looks like a wiring fault.
#
# ===========================================================================

import argparse
import json
import sys
import time
from pathlib import Path

try:
    import pigpio
except ImportError:
    sys.exit("pigpio is not installed. Run: sudo apt install python3-pigpio")

CONFIG_FILE = Path(__file__).with_name("lightning_config.json")

# Matches Config defaults in lightning_detector.py, used when the config file
# does not name them.
DEFAULT_TX_PIN = 26
DEFAULT_BAUD = 9600


def load_settings():
    """Read the pin and baud the detector itself would use.

    Read from the same file rather than accepted as arguments, so the probe
    cannot test a pin the service will not actually drive - which would prove
    the wiring correct while leaving the unit silent.
    """
    tx_pin, baud = DEFAULT_TX_PIN, DEFAULT_BAUD
    try:
        cfg = json.loads(CONFIG_FILE.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        print(f"  note: could not read {CONFIG_FILE.name} ({exc}); using defaults")
        return tx_pin, baud
    tx_pin = int(cfg.get("campbell_uart_tx_pin", tx_pin))
    baud = int(cfg.get("campbell_uart_baud", baud))
    if not cfg.get("campbell_uart_enabled", False):
        print("  note: campbell_uart_enabled is false in the config, so the "
              "service will NOT drive this pin in normal operation.")
    return tx_pin, baud


def connect():
    pi = pigpio.pi()
    if not pi.connected:
        sys.exit("pigpio daemon is not running. Run: sudo systemctl start pigpiod")
    return pi


def toggle(pi, tx_pin, seconds, period):
    """Square wave slow enough to read on a cheap meter.

    One second high, one second low by default. A meter set to DC volts shows it
    stepping between roughly 0 V and 3.3 V, which is unambiguous on the right
    terminal and flat on every other one.
    """
    print(f"Toggling BCM {tx_pin} every {period:.1f}s for {seconds}s.")
    print("Probe each screw terminal against GND. The one that steps between "
          "0 V and 3.3 V is the Campbell TX terminal. Label it.")
    pi.set_mode(tx_pin, pigpio.OUTPUT)
    end = time.monotonic() + seconds
    level = 1
    try:
        while time.monotonic() < end:
            pi.write(tx_pin, level)
            print(f"  BCM {tx_pin} = {'HIGH (3.3 V)' if level else 'LOW (0 V)'}")
            level ^= 1
            time.sleep(period)
    finally:
        # Leave it idle-high, which is the UART resting state the detector also
        # leaves it in. Idle-low would read as a continuous break to the logger.
        pi.write(tx_pin, 1)
        print(f"  BCM {tx_pin} left idle high, as a UART line should rest.")


def send(pi, tx_pin, baud, count):
    """Send test records in the detector's exact wire format.

    "L,<distance_km>,<energy>\\r\\n" - the same string send_lightning produces,
    so a logger program that parses the real thing parses this too. A distance of
    99 is deliberately implausible as weather, so a record that reaches a live
    logger is recognisable as a commissioning test rather than a strike.
    """
    print(f"Sending {count} test record(s) on BCM {tx_pin} at {baud} baud, 8N1.")
    pi.set_mode(tx_pin, pigpio.OUTPUT)
    pi.write(tx_pin, 1)
    time.sleep(0.05)
    for i in range(count):
        record = f"L,99,{123400 + i}\r\n".encode("ascii")
        wid = -1
        try:
            pi.wave_add_new()
            pi.wave_add_serial(tx_pin, baud, record)
            wid = pi.wave_create()
            if wid < 0:
                raise RuntimeError(f"wave_create failed ({wid})")
            pi.wave_send_once(wid)
            started = time.monotonic()
            while pi.wave_tx_busy():
                if time.monotonic() - started > 1.0:
                    print("  warning: transmission did not complete in 1s")
                    break
                time.sleep(0.001)
            print(f"  sent: {record!r}")
        finally:
            if wid >= 0:
                pi.wave_delete(wid)
        time.sleep(0.5)
    print("Check the logger's serial input. Nothing arriving means the wiring, "
          "the baud rate or the ground reference, in that order of likelihood.")


def main():
    ap = argparse.ArgumentParser(
        description="Identify and verify the Campbell UART terminal on the "
                    "Terminal 2 Click in socket 2.")
    ap.add_argument("--toggle", action="store_true",
                    help="square-wave the pin so the terminal can be found")
    ap.add_argument("--send", action="store_true",
                    help="send test records in the detector's wire format")
    ap.add_argument("--seconds", type=int, default=30,
                    help="how long to toggle for (default 30)")
    ap.add_argument("--period", type=float, default=1.0,
                    help="seconds per half cycle while toggling (default 1.0)")
    ap.add_argument("--count", type=int, default=3,
                    help="how many test records to send (default 3)")
    args = ap.parse_args()

    if not (args.toggle or args.send):
        ap.error("choose --toggle to find the terminal, or --send to test it")

    tx_pin, baud = load_settings()
    # A ground reference is required for either test to mean anything, and it is
    # the most common omission on a first install.
    print("Ground the logger and the Pi together before trusting any result.")
    pi = connect()
    try:
        if args.toggle:
            toggle(pi, tx_pin, args.seconds, args.period)
        if args.send:
            send(pi, tx_pin, baud, args.count)
    finally:
        pi.stop()


if __name__ == "__main__":
    main()

# ===========================================================================
#  END OF PROGRAM
# ===========================================================================
